const FETCH_DATA = "FETCH_DATA";
const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCESSES";
const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
const GET_CURRENT_IMAGE = "GET_CURRENT_IMAGE";
const GET_CURRENT_HERO = "GET_CURRENT_HERO";
export {
  FETCH_DATA,
  FETCH_DATA_SUCCESS,
  FETCH_DATA_ERROR,
  GET_CURRENT_IMAGE,
  GET_CURRENT_HERO
};
